
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WELCOME
 */
public class cOwnerPage extends javax.swing.JFrame {

    /**
     * Creates new form c
     */
    public cOwnerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ItemNameTF = new javax.swing.JTextField();
        PriceTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ItemCodeTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ModifyICodeTF = new javax.swing.JTextField();
        ModifyINameTF = new javax.swing.JTextField();
        ModifyIPriceTF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DeleteICodeTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AddEmplName = new javax.swing.JTextField();
        AddEmpMbNo = new javax.swing.JTextField();
        AddEmpCity = new javax.swing.JTextField();
        AddEmpState = new javax.swing.JTextField();
        AddEmpSalary = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AddEmpDsg = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FireEmpName = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        EmpDetailName = new javax.swing.JTextField();
        EmpDetailMbNo = new javax.swing.JTextField();
        EmpDetailCity = new javax.swing.JTextField();
        EmpDetailState = new javax.swing.JTextField();
        EmpDetailSalary = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        EmpDetailDOJ = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        EmpDetailDOB = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        EmpDetailDsg = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Item Name");

        jLabel4.setText("Price");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Item code");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(73, 73, 73)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ItemCodeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(ItemNameTF)
                                    .addComponent(PriceTF)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ItemCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ItemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Food Item", jPanel3);

        jLabel6.setText("Item Code");

        jLabel7.setText("Item Name");

        jLabel8.setText("Price");

        ModifyICodeTF.setEditable(false);

        jButton3.setText("modify");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Display");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModifyICodeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(ModifyINameTF)
                            .addComponent(ModifyIPriceTF)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton7)
                        .addGap(99, 99, 99)
                        .addComponent(jButton3)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ModifyICodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ModifyINameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ModifyIPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modify Food Item", jPanel5);

        jLabel5.setText("Item Code");

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addGap(60, 60, 60)
                        .addComponent(DeleteICodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton2)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DeleteICodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jButton2)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Food Item", jPanel4);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Employee Name");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel11.setText("Mobile Number");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel12.setText("City");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel13.setText("state");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel14.setText("Salary");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel15.setText("Date of Join");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        jPanel8.add(AddEmplName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, -1));
        jPanel8.add(AddEmpMbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, -1));
        jPanel8.add(AddEmpCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, -1));
        jPanel8.add(AddEmpState, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, -1));
        jPanel8.add(AddEmpSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 140, -1));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel25.setText("Date of birth");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel27.setText("Designation");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        AddEmpDsg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "manager", "Cook", "Waiter", "Recipy server", "Sweeper" }));
        AddEmpDsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEmpDsgMouseClicked(evt);
            }
        });
        AddEmpDsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpDsgActionPerformed(evt);
            }
        });
        AddEmpDsg.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                AddEmpDsgVetoableChange(evt);
            }
        });
        jPanel8.add(AddEmpDsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 155, -1));
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        jTabbedPane2.addTab("Add Employee", jPanel8);

        jLabel16.setText("Employee name");

        jLabel17.setText("Leave date");

        jButton4.setText("Fire");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(54, 54, 54)
                        .addComponent(FireEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton4)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(FireEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(59, 59, 59)
                .addComponent(jButton4)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Fire Employee", jPanel9);

        jLabel18.setText("Employee name");

        jLabel19.setText("Mobile Number");

        jLabel20.setText("City");

        jLabel21.setText("state");

        jLabel22.setText("Salary");

        jLabel23.setText("Date of join");

        jButton5.setText("display");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel26.setText("Date of birth");

        jButton9.setText("modify");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel2.setText("Designation");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmpDetailState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(EmpDetailMbNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpDetailCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpDetailDOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpDetailDOJ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpDetailSalary)
                            .addComponent(EmpDetailDsg))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton9))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(28, 28, 28)
                        .addComponent(EmpDetailName)
                        .addGap(207, 207, 207))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(EmpDetailName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton5)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(EmpDetailMbNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpDetailDsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)))))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(EmpDetailCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(EmpDetailState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(EmpDetailSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(EmpDetailDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(EmpDetailDOJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );

        jTabbedPane2.addTab("Employee Detail", jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Employee", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 450, 410));

        jButton8.setText("Log Out");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 900, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Name=JOptionPane.showInputDialog("enter Employee and the record will be displayed");
        String EName="",Mnumber="",City="",State="",Salary="",DateofJoin="",DateofBirth="",dsg="";
        try{
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
            st=con1.createStatement();
            String qu="Select * from employee where empname='"+Name+"';";
            ResultSet rs;
            rs=st.executeQuery(qu);
            while(rs.next()){
                EName=rs.getString(1);
                Mnumber=rs.getString(2);
                dsg=rs.getString(3);
                Salary=rs.getString(4);
                City=rs.getString(5);
                State=rs.getString(6);
                DateofJoin=rs.getString(7);
                DateofBirth=rs.getString(8);
            }
            if(Name.equals(EName)){
                EmpDetailName.setText(""+EName);
                EmpDetailMbNo.setText(""+Mnumber);
                EmpDetailDsg.setText(""+dsg);
                EmpDetailCity.setText(""+City);
                EmpDetailState.setText(""+State);
                EmpDetailSalary.setText(""+Salary);
                EmpDetailDOB.setText(""+DateofJoin);
                EmpDetailDOJ.setText(""+DateofBirth);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Item does not exist with code = "+Name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Ename=FireEmpName.getText();
        String LDate=((JTextField)FireEmpLD.getDateEditor().getUiComponent()).getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
            st=con1.createStatement();
            String qu="delete from employee where empname='"+Ename+"';";
            String q="insert into exemployee values('"+Ename+"','"+LDate+"');"; 
            st.executeUpdate(q);
            st.executeUpdate(qu); 
            JOptionPane.showMessageDialog(this,Ename + " is fired");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Name=AddEmplName.getText();
        String MNo=AddEmpMbNo.getText();
        String City=AddEmpCity.getText();
        String State=AddEmpState.getText();
        String SalaryS=AddEmpSalary.getText();
        String dateB=((JTextField)AddEmpDOB.getDateEditor().getUiComponent()).getText();
        String dateJ=((JTextField)AddEmpDOJ.getDateEditor().getUiComponent()).getText();
        String dsg=(String) AddEmpDsg.getSelectedItem();
        if(Name.isEmpty()||City.isEmpty()||State.isEmpty()||dateB.isEmpty()||dateJ.isEmpty()||dsg.isEmpty()||MNo.isEmpty()||SalaryS.isEmpty()){
        JOptionPane.showMessageDialog(this,"Please enter all the informations");
        }
        else 
        {
        try{
            double Salary=Double.parseDouble(SalaryS);            
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
            st=(Statement) con1.createStatement();
            String qu="insert into employee values ('"+Name+"','"+MNo+"','"+dsg+"','"+Salary+"','"+City+"','"+State+"','"+dateJ+"','"+dateJ+"');";
            st.executeUpdate(qu);
            JOptionPane.showMessageDialog(this,Name + " is Added Successfully");
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        AddEmplName.setText("");
        AddEmpMbNo.setText("");
        AddEmpCity.setText("");
        AddEmpState.setText("");
        AddEmpSalary.setText("");
        AddEmpDsg.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Icode=DeleteICodeTF.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
            st=con1.createStatement();
            String qu="delete from food where item_code='"+Icode+"';";
            st.executeUpdate(qu);
            JOptionPane.showMessageDialog(this,"Item with ItemCode:"+Icode + " is removed");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        DeleteICodeTF.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String Code=JOptionPane.showInputDialog("enter Item_Code and the record will be displayed");
        String IName="",IPrice="",ICode="";
        try{
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
            st=con1.createStatement();
            String qu="Select * from FOOD where item_code='"+Code+"';";
            ResultSet rs;
            rs=st.executeQuery(qu);
            while(rs.next()){
                ICode=rs.getString("Item_code");
                IName=rs.getString("item_name");
                IPrice=rs.getString("price");
            }
            if(Code.equals(ICode)){
                ModifyICodeTF.setText(""+ICode);
                ModifyINameTF.setText(IName);
                ModifyIPriceTF.setText(""+IPrice);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Item does not exist with code = "+Code);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int c=JOptionPane.showConfirmDialog(this,"Do you want to modify?","Confirm",JOptionPane.YES_NO_CANCEL_OPTION);
        if(c==0){
            int ICode=Integer.parseInt(ModifyICodeTF.getText());
            String IName=ModifyINameTF.getText();
            double IPrice=Double.parseDouble(ModifyIPriceTF.getText());
            try{
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st;
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
                st=con1.createStatement();
                String qu="update food set item_name='"+IName+"',price='"+IPrice+"' where item_code='"+ICode+"';";
                st.executeUpdate(qu);
                JOptionPane.showMessageDialog(this,"Record successfully Modified");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            ModifyICodeTF.setText("");
            ModifyINameTF.setText("");
            ModifyIPriceTF.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ICode=Integer.parseInt(ItemCodeTF.getText());
        String IName=ItemNameTF.getText();
        double IPrice=Double.parseDouble(PriceTF.getText());
        if(IName.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter details");
        }
        else
        {
            try{
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st;
                con1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
                st=(Statement) con1.createStatement();
                String qu="insert into food values ('"+ICode+"','"+IName+"','"+IPrice+"');";
                st.executeUpdate(qu);
                JOptionPane.showMessageDialog(this,IName +" is Added Successfully");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            ItemCodeTF.setText("");
            ItemNameTF.setText("");
            PriceTF.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        bLoginPage a=new bLoginPage();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AddEmpDsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEmpDsgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddEmpDsgMouseClicked

    private void AddEmpDsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpDsgActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddEmpDsgActionPerformed

    private void AddEmpDsgVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_AddEmpDsgVetoableChange
        // TODO add your handling code here:

    }//GEN-LAST:event_AddEmpDsgVetoableChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int c=JOptionPane.showConfirmDialog(this,"Do you want to modify?","Confirm",JOptionPane.YES_NO_CANCEL_OPTION);
        if(c==0){
            String EmpName=EmpDetailName.getText();
            String MbNo=EmpDetailMbNo.getText();
            String Dsg=EmpDetailDsg.getText();
            String City=EmpDetailCity.getText();
            String State=EmpDetailState.getText();
            String Salary=EmpDetailSalary.getText();
            String DOB=EmpDetailDOB.getText();
            String DOJ=EmpDetailDOJ.getText();
            try{
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st;
                con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
                st=con1.createStatement();
                String qu="update employee set empname='"+EmpName+"',mobilenumber='"+MbNo+"',Designation='"+Dsg+"',City='"+City+"',State='"+State+"',Salary='"+Salary+"',DateofJoin='"+DOJ+"',DateOfBirth='"+DOB+"' where EmpName='"+EmpName+"';";
                st.executeUpdate(qu);
                JOptionPane.showMessageDialog(this,"Record successfully Modified");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
            ModifyICodeTF.setText("");
            ModifyINameTF.setText("");
            ModifyIPriceTF.setText("");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cOwnerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cOwnerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddEmpCity;
    private javax.swing.JComboBox<String> AddEmpDsg;
    private javax.swing.JTextField AddEmpMbNo;
    private javax.swing.JTextField AddEmpSalary;
    private javax.swing.JTextField AddEmpState;
    private javax.swing.JTextField AddEmplName;
    private javax.swing.JTextField DeleteICodeTF;
    private javax.swing.JTextField EmpDetailCity;
    private javax.swing.JTextField EmpDetailDOB;
    private javax.swing.JTextField EmpDetailDOJ;
    private javax.swing.JTextField EmpDetailDsg;
    private javax.swing.JTextField EmpDetailMbNo;
    private javax.swing.JTextField EmpDetailName;
    private javax.swing.JTextField EmpDetailSalary;
    private javax.swing.JTextField EmpDetailState;
    private javax.swing.JTextField FireEmpName;
    private javax.swing.JTextField ItemCodeTF;
    private javax.swing.JTextField ItemNameTF;
    private javax.swing.JTextField ModifyICodeTF;
    private javax.swing.JTextField ModifyINameTF;
    private javax.swing.JTextField ModifyIPriceTF;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
