
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author WELCOME
 */
public class eBilling extends javax.swing.JFrame {

    static String TbNo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form eBilling
     */
    public eBilling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TbNoTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ICodeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        INameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        QtyTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IPriceTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BillNoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TotalTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TaxTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TaxAmtTF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        NetAmtTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Table Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        TbNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbNoTFActionPerformed(evt);
            }
        });
        getContentPane().add(TbNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("FoodItem Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        ICodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICodeTFActionPerformed(evt);
            }
        });
        getContentPane().add(ICodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Food Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        INameTF.setEditable(false);
        getContentPane().add(INameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Qty");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        QtyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtyTFActionPerformed(evt);
            }
        });
        getContentPane().add(QtyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Price for One");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        IPriceTF.setEditable(false);
        getContentPane().add(IPriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 70, -1));

        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Qty", "Price ", "Total"
            }
        ));
        jScrollPane1.setViewportView(BillTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 210));

        BillList.setModel(new DefaultListModel());
        BillList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BillList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillListMouseClicked(evt);
            }
        });
        BillList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                BillListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(BillList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 120, 210));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Bill Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 20, 100, -1));
        getContentPane().add(BillNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 40, -1));
        getContentPane().add(TotalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Tax(%)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));
        getContentPane().add(TaxTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Tax Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));
        getContentPane().add(TaxAmtTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 80, -1));

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 153));
        jLabel10.setText("NetAmount");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));
        getContentPane().add(NetAmtTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 80, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue_white_line_bright_144_602x339.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 760, 530));

        jMenu1.setText("<-Back                                        ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Parcel                                                 ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Waiting list                                      ");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Employee                ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Logout        ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dBranchMainPage a = new dBranchMainPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        fParcel a = new fParcel();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        gWaitingList a = new gWaitingList();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        hEmployee a = new hEmployee();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int t = BillTable.getRowCount();
        String TbNo = TbNoTF.getText();
        String BillNo=BillNoTF.getText();
        int i;
        DefaultTableModel tm = (DefaultTableModel) BillTable.getModel();
        try {
            Object ItemCode = new Object();
            Object ItmName = new Object();
            Object Qty = new Object();
            Object Price = new Object();
            Object Total = new Object();
            Object NetAmt=NetAmtTF.getText();
            for (i = 0; i < t; i++) {

                ItemCode = BillTable.getValueAt(i, 0);
                ItmName = BillTable.getValueAt(i, 1);
                Qty = BillTable.getValueAt(i, 2);
                Price = BillTable.getValueAt(i, 3);
                Total = BillTable.getValueAt(i, 4);
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st1;
                con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
                st1 = (Statement) con1.createStatement();
                String qu = "insert into bill values('" + BillNo + "','" + TbNo + "'," + ItemCode + ",'" + ItmName + "'," + Qty + "," + Price + "," + Total + ");";
                st1.executeUpdate(qu);

            }
            tm.setRowCount(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        DefaultListModel df = (DefaultListModel) BillList.getModel();
        df.addElement(TbNo);
        TbNoTF.setText("");
        BillNoTF.setText("");
        ICodeTF.requestFocus();
        TotalTF.setText("");
        TaxTF.setText("");
        TaxAmtTF.setText("");
        NetAmtTF.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ICodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICodeTFActionPerformed
        // TODO add your handling code here:
        int ItmCode = Integer.parseInt(ICodeTF.getText());
        String ItmName = "";
        int price = 0;
        try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from food where item_code='" + ItmCode + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            while (rs.next()) {
                ItmName = rs.getString(2);
                price = rs.getInt(3);
            }
            INameTF.setText(ItmName);
            IPriceTF.setText("" + price);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        QtyTF.requestFocus();
    }//GEN-LAST:event_ICodeTFActionPerformed

    private void QtyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtyTFActionPerformed
        // TODO add your handling code here:
        double qty = Double.parseDouble(QtyTF.getText());
        int price = Integer.parseInt(IPriceTF.getText());
        double total = qty * price;

        String TbNo = TbNoTF.getText();
        int ItmCode = Integer.parseInt(ICodeTF.getText());
        String ItmName = INameTF.getText();
        if (TbNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "please enter TableNumber");
        } else {
            Object[] sn = {ItmCode, ItmName, qty, price, total};
            DefaultTableModel tm = (DefaultTableModel) BillTable.getModel();
            tm.addRow(sn);
            ICodeTF.setText("");
            INameTF.setText("");
            QtyTF.setText("");
            IPriceTF.setText("");
        }
        ICodeTF.requestFocus();
    }//GEN-LAST:event_QtyTFActionPerformed

    private void BillListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_BillListValueChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_BillListValueChanged

    private void BillListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillListMouseClicked
        // TODO add your handling code here:
        String TbNo = (String) BillList.getSelectedValue();
        String BillNo = "";
        String ItmCode = "";
        String ItmName = "";
        String Price = "";
        String Qty = "";
        double Total = 0;
        try {
            Class.forName("java.sql.DriverManager");

            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from bill where TableNo='" + TbNo + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            while (rs.next()) {
                BillNo=rs.getString(1);
                ItmCode = rs.getString(3);
                ItmName = rs.getString(4);
                Price = rs.getString(6);
                Qty = rs.getString(5);
                Total = rs.getDouble(7);
                Object[] sn = {ItmCode, ItmName, Qty, Price, Total};
                DefaultTableModel tm = (DefaultTableModel) BillTable.getModel();
                tm.addRow(sn);
            }
            BillNoTF.setText(BillNo);
         try
        {
         Class.forName("java.sql.DriverManager");
         Connection con;
         Statement st1;
         con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
         st1=con1.createStatement();
         String qu1="delete from bill where tableNo='"+TbNo+"';";
         st1.executeUpdate(qu1);
         DefaultTableModel tm1=(DefaultTableModel) BillTable.getModel();}
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
            DefaultListModel df = (DefaultListModel) BillList.getModel();
            df.removeElement(TbNo);
            TbNoTF.setText(TbNo);

        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_BillListMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int t = BillTable.getRowCount();
        String TbNo = TbNoTF.getText();
        String BillNo=BillNoTF.getText();
        double NetAmt=Double.parseDouble(NetAmtTF.getText());
        int i;
        try {
            int ItemCode = 0;
            String ItmName = "";
            double Qty = 0;
            int Price = 0;
            double Total =0;
            
            for (i = 0; i < t; i++){

                ItemCode =(Integer) BillTable.getValueAt(i, 0);
                ItmName =(String) BillTable.getValueAt(i, 1);
                Qty =(double) BillTable.getValueAt(i, 2);
                Price =(Integer) BillTable.getValueAt(i, 3);
                Total =(double) BillTable.getValueAt(i, 4);
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st1;
                con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
                st1 = (Statement) con1.createStatement();
                String qu = "insert into billHistory values('" + BillNo + "','" + TbNo + "'," + ItemCode + ",'" + ItmName + "'," + Qty + "," + Price + "," + Total + ","+NetAmt+");";
                st1.executeUpdate(qu);
            }
        DefaultTableModel tm1=(DefaultTableModel) BillTable.getModel();
        int length=tm1.getRowCount();
        for(int j=0;j<length;j++){
            tm1.removeRow(0);
            }
            tm1.setRowCount(0);
            
         Class.forName("java.sql.DriverManager");
         Connection con;
         Statement st;
         con=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
         st=con.createStatement();
         String qu1="delete from bill where tableNo='"+TbNo+"';";
         st.executeUpdate(qu1);
        TbNoTF.requestFocus();
        JOptionPane.showMessageDialog(this,"Thank You ");
        TbNoTF.setText("");
        ICodeTF.setText("");
        INameTF.setText("");
        QtyTF.setText("");
        IPriceTF.setText("");
        BillNoTF.setText("");} 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        bLoginPage a=new bLoginPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void TbNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbNoTFActionPerformed
        // TODO add your handling code here:
        ICodeTF.requestFocus();
    }//GEN-LAST:event_TbNoTFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double Amt=0;
        for(int i=0;i<BillTable.getRowCount();i++){
            double value=(double) BillTable.getValueAt(i,4);
            Amt=Amt+value;
        }
        double tax=Amt*0.15;
        double NetAmt=Amt-tax;
        TotalTF.setText(""+Amt);
        TaxTF.setText("15%");
        TaxAmtTF.setText(""+tax);
        NetAmtTF.setText(""+NetAmt);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> BillList;
    private javax.swing.JTextField BillNoTF;
    private javax.swing.JTable BillTable;
    private javax.swing.JTextField ICodeTF;
    private javax.swing.JTextField INameTF;
    private javax.swing.JTextField IPriceTF;
    private javax.swing.JTextField NetAmtTF;
    private javax.swing.JTextField QtyTF;
    private javax.swing.JTextField TaxAmtTF;
    private javax.swing.JTextField TaxTF;
    private javax.swing.JTextField TbNoTF;
    private javax.swing.JTextField TotalTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
