
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class fParcel extends javax.swing.JFrame {

    /**
     * Creates new form parcel
     */
    public fParcel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ICodeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        INameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IPriceTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IQtyTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Parceltable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        PhNoTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddressTA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ParcelList = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Parcel service");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 335, 54));

        jLabel2.setText("Icode");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 30));

        ICodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICodeTFActionPerformed(evt);
            }
        });
        getContentPane().add(ICodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, -1));

        jLabel3.setText("Iname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 70, -1));

        INameTF.setEditable(false);
        INameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INameTFActionPerformed(evt);
            }
        });
        getContentPane().add(INameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 70, -1));

        jLabel4.setText("price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 50, 20));

        IPriceTF.setEditable(false);
        getContentPane().add(IPriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, -1));

        jLabel5.setText("Qty");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        IQtyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IQtyTFActionPerformed(evt);
            }
        });
        getContentPane().add(IQtyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 100, 20));

        Parceltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Item price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(Parceltable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 310, 480, 142));

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        jLabel7.setText("Phone number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        getContentPane().add(PhNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, -1));

        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        AddressTA.setColumns(20);
        AddressTA.setRows(5);
        jScrollPane2.setViewportView(AddressTA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 120));

        ParcelList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParcelListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ParcelList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 120, 280));

        jButton2.setText("Save");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parcelimg.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 640));

        jMenu1.setText("   <-Back                                            ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("     Billing                                      ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Employee                                    ");
        jMenu3.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu3MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Waiting List                    ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Logout        ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dBranchMainPage a=new dBranchMainPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int t = Parceltable.getRowCount();
        String PhNo = PhNoTF.getText();
        String Address=AddressTA.getText();
        int i;
        DefaultTableModel tm = (DefaultTableModel) Parceltable.getModel();
        try {
            Object ItemCode = new Object();
            Object ItmName = new Object();
            Object Qty = new Object();
            Object Price = new Object();
            Object Total = new Object();
            for (i = 0; i < t; i++) {

                ItemCode = Parceltable.getValueAt(i, 0);
                ItmName = Parceltable.getValueAt(i, 1);
                Qty = Parceltable.getValueAt(i, 3);
                Price = Parceltable.getValueAt(i, 2);
                Total = Parceltable.getValueAt(i, 4);
                Class.forName("java.sql.DriverManager");
                Connection con1;
                Statement st1;
                con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
                st1 = (Statement) con1.createStatement();
                String qu = "insert into Parcel values('" + PhNo + "'," + ItemCode + ",'" + ItmName + "'," + Qty + "," + Price + "," + Total + ",'" + Address + "');";
                st1.executeUpdate(qu);

            }
            tm.setRowCount(0);

        PhNoTF.setText("");
        AddressTA.setText("");
        PhNo = "";
JOptionPane.showMessageDialog(this,"Thank you");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu3MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu3MenuKeyPressed
        // TODO add your handling code here:
        hEmployee a=new hEmployee();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MenuKeyPressed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        gWaitingList a=new gWaitingList();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void INameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INameTFActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        eBilling a=new eBilling();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void ICodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICodeTFActionPerformed
        // TODO add your handling code here:
        int ItmCode = Integer.parseInt(ICodeTF.getText());
        String ItmName = "";
        int price = 0;
        try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from food where item_code='" + ItmCode + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            while (rs.next()) {
                ItmName = rs.getString(2);
                price = rs.getInt(3);
            }
            INameTF.setText(ItmName);
            IPriceTF.setText("" + price);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        IQtyTF.requestFocus();
    }//GEN-LAST:event_ICodeTFActionPerformed

    private void IQtyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IQtyTFActionPerformed
        // TODO add your handling code here:
        double qty = Double.parseDouble(IQtyTF.getText());
        int price = Integer.parseInt(IPriceTF.getText());
        double total = qty * price;

        String PhNo = PhNoTF.getText();
        int ItmCode = Integer.parseInt(ICodeTF.getText());
        String ItmName = INameTF.getText();
        String Address=AddressTA.getText();
            Object[] sn = {ItmCode, ItmName,price,qty, total};
            DefaultTableModel tm = (DefaultTableModel) Parceltable.getModel();
            tm.addRow(sn);
            ICodeTF.setText("");
            INameTF.setText("");
            IPriceTF.setText("");
            IQtyTF.setText("");
        
    }//GEN-LAST:event_IQtyTFActionPerformed

    private void ParcelListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParcelListMouseClicked
        // TODO add your handling code here:
        String PhNo = (String) ParcelList.getSelectedValue();
        String ItmCode = "";
        String ItmName = "";
        String Price = "";
        String Qty = "";
        String Total = "";
        String Address="";
        try {
            Class.forName("java.sql.DriverManager");

            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from khana where phonenumber='" + PhNo+ "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            while (rs.next()) {
                ItmCode = rs.getString(2);
                ItmName = rs.getString(3);
                Price = rs.getString(5);
                Qty = rs.getString(4);
                Total = rs.getString(6);
                Address=rs.getString(7);
                Object[] sn = {ItmCode, ItmName, Qty, Price, Total};
                DefaultTableModel tm = (DefaultTableModel) Parceltable.getModel();
                tm.addRow(sn);
                AddressTA.setText(Address);
            }
         try
        {
         Class.forName("java.sql.DriverManager");
         Connection con;
         Statement st1;
         con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist","root","admin");
         st1=con1.createStatement();
         String qu1="delete from parcel where phonenumber='"+PhNo+"';";
         st1.executeUpdate(qu1);
         DefaultTableModel tm1=(DefaultTableModel) Parceltable.getModel();;
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
            DefaultListModel df = (DefaultListModel) ParcelList.getModel();
            df.removeElement(PhNo);
            PhNoTF.setText(PhNo);

        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_ParcelListMouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        bLoginPage a=new bLoginPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fParcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fParcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fParcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fParcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fParcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTA;
    private javax.swing.JTextField ICodeTF;
    private javax.swing.JTextField INameTF;
    private javax.swing.JTextField IPriceTF;
    private javax.swing.JTextField IQtyTF;
    private javax.swing.JList<String> ParcelList;
    private javax.swing.JTable Parceltable;
    private javax.swing.JTextField PhNoTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
