
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class hEmployee extends javax.swing.JFrame {

    /**
     * Creates new form employees
     */
    public hEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ManagerTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ManagerTA = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DsgCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmpTA = new javax.swing.JTextArea();
        EmpNameCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 3, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 102));
        jLabel1.setText("EMPLOYEES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 350, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Manager");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        ManagerTF.setEditable(false);
        ManagerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerTFActionPerformed(evt);
            }
        });
        jPanel1.add(ManagerTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 249, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 100, 20));

        ManagerTA.setEditable(false);
        ManagerTA.setColumns(20);
        ManagerTA.setRows(5);
        jScrollPane3.setViewportView(ManagerTA);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 325, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man.PNG"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("AR DELANEY", 2, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managbg.jpg"))); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 500));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Vivaldi", 2, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Other employees");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        DsgCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cook", "Waiter", "Recipy server", "Sweeper" }));
        DsgCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DsgCBMouseClicked(evt);
            }
        });
        DsgCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsgCBActionPerformed(evt);
            }
        });
        DsgCB.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                DsgCBVetoableChange(evt);
            }
        });
        jPanel2.add(DsgCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 155, -1));

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 130, -1));

        EmpTA.setEditable(false);
        EmpTA.setColumns(20);
        EmpTA.setRows(5);
        jScrollPane2.setViewportView(EmpTA);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 330, 130));

        EmpNameCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpNameCBMouseClicked(evt);
            }
        });
        EmpNameCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNameCBActionPerformed(evt);
            }
        });
        EmpNameCB.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                EmpNameCBVetoableChange(evt);
            }
        });
        jPanel2.add(EmpNameCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 250, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cook1.PNG"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managbg.jpg"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 440, 500));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/r.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 660));

        jMenu1.setText("   <-Back                                                ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Billing                                  ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Parcel                                            ");
        jMenu3.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu3MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Waiting List           ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Logout        ");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerTFActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dBranchMainPage a = new dBranchMainPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu3MenuKeyPressed
        // TODO add your handling code here:
        fParcel a = new fParcel();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu3MenuKeyPressed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        gWaitingList a = new gWaitingList();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        eBilling a = new eBilling();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        // TODO add your handling code here:
        String name = "";
        String mno = "";
        String city = "";
        String state = "";
        String Salary = "";
        String doj = "";
        String dob = "";
        String dsg = "manager";
        try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from employee where designation = '" + dsg + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            while (rs.next()) {
                name=rs.getString(1);
                mno = rs.getString(2);
                Salary = rs.getString(4);
                city = rs.getString(5);
                state = rs.getString(6);
                doj = rs.getString(7);
                dob = rs.getString(8);

            }
            ManagerTF.setText(name);
            ManagerTA.setText("Mobilenumber=" + mno + "\n" + "City=" + city + "\n State=" + state + "\n Salary=" + Salary + "\n Date of Birth=" + dob + "\n Date of Join=" + doj);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jLabel9MouseMoved

    private void DsgCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsgCBActionPerformed
        // TODO add your handling code here:
        Object dsg = DsgCB.getSelectedItem();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from employee where designation='" + dsg + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            String name;
            EmpNameCB.removeAllItems();
           
                while (rs.next()) {
                    name = rs.getString(1);
                    EmpNameCB.addItem(name);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DsgCBActionPerformed

    private void EmpNameCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNameCBActionPerformed
        // TODO add your handling code here:
        Object name = EmpNameCB.getSelectedItem();

        try {
            Class.forName("java.sql.DriverManager");
            Connection con1;
            Statement st;
            con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/optimist", "root", "admin");
            st = (Statement) con1.createStatement();
            String qu = "select * from employee where Empname='" + name + "';";
            ResultSet rs;
            rs = st.executeQuery(qu);
            String mno = "";
            String city = "";
            String state = "";
            String Salary = "";
            String doj = "";
            String dob = "";
            String dsg = "";
            while (rs.next()) {
                mno = rs.getString(2);
                dsg = rs.getString(3);
                Salary = rs.getString(4);
                city = rs.getString(5);
                state = rs.getString(6);
                doj = rs.getString(7);
                dob = rs.getString(8);
            }
            
            EmpTA.setText("Mobilenumber=" + mno + "\n" + "City=" + city + "\n State=" + state + "\n Salary=" + Salary + "\n Date of Birth=" + dob + "\n Date of Join=" + doj);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_EmpNameCBActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        bLoginPage a=new bLoginPage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void EmpNameCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpNameCBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpNameCBMouseClicked

    private void DsgCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DsgCBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DsgCBMouseClicked

    private void DsgCBVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_DsgCBVetoableChange
        // TODO add your handling code here:
        

    }//GEN-LAST:event_DsgCBVetoableChange

    private void EmpNameCBVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_EmpNameCBVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EmpNameCBVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new hEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DsgCB;
    private javax.swing.JComboBox<String> EmpNameCB;
    private javax.swing.JTextArea EmpTA;
    private javax.swing.JTextArea ManagerTA;
    private javax.swing.JTextField ManagerTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
